export const SAVE_DOCUMENT_REQUEST = "SAVE_DOCUMENT_REQUEST";
export const FETCH_DOCUMENT_REQUEST = "FETCH_DOCUMENT_REQUEST";
export const UPDATE_DOCUMENT_REQUEST = "UPDATE_DOCUMENT_REQUEST";
export const DELETE_DOCUMENT_REQUEST = "DELETE_DOCUMENT_REQUEST";
export const DOCUMENT_SUCCESS = "DOCUMENT_SUCCESS";
export const DOCUMENT_FAILURE = "DOCUMENT_FAILURE";
export const DOCUMENT_REQUEST = "DOCUMENT_REQUEST";