export const SAVE_PROCESS_REQUEST = "SAVE_PROCESS_REQUEST";
export const FETCH_PROCESS_REQUEST = "FETCH_PROCESS_REQUEST";
export const UPDATE_PROCESS_REQUEST = "UPDATE_PROCESS_REQUEST";
export const DELETE_PROCESS_REQUEST = "DELETE_PROCESS_REQUEST";
export const PROCESS_SUCCESS = "PROCESS_SUCCESS";
export const PROCESS_FAILURE = "PROCESS_FAILURE";
export const PROCESS_REQUEST = "PROCESS_REQUEST";
