export const SAVE_AUDIT_REQUEST = "SAVE_AUDIT_REQUEST";
export const FETCH_AUDIT_REQUEST = "FETCH_AUDIT_REQUEST";
export const UPDATE_AUDIT_REQUEST = "UPDATE_AUDIT_REQUEST";
export const DELETE_AUDIT_REQUEST = "DELETE_AUDIT_REQUEST";
export const AUDIT_SUCCESS = "AUDIT_SUCCESS";
export const AUDIT_FAILURE = "AUDIT_FAILURE";
export const AUDIT_REQUEST = "AUDIT_REQUEST";